"""Time-series dataset splitting module for financial chart research.

Complies with AGENTS.md:
- Strict chronological split (Train < Val < Test) to eliminate look-ahead bias.
- Absolute ban on random shuffle.
- Embargo/purge buffer between splits to prevent candle overlap.
- Clean JSONL export compatible with FinancialChartDataset.
- Follows Ponytail principle: minimal, stdlib-first, robust.
"""
import json
import logging
from pathlib import Path
from typing import Dict, List, Any, Optional, Tuple
import yaml
import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

DEFAULT_INSTRUCTION = "Hãy phân tích biểu đồ kỹ thuật này và đề xuất phương án xử lý."


def load_config(config_path: str) -> Dict[str, Any]:
    """Load dataset splitting configuration from YAML file."""
    with open(config_path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def split_series_chronological(
    df_group: pd.DataFrame,
    train_ratio: float = 0.70,
    val_ratio: float = 0.15,
    test_ratio: float = 0.15,
    purge_windows: int = 1
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Split a single asset/timeframe sequence chronologically with embargo purge.

    Args:
        df_group: DataFrame for a single asset/symbol/timeframe, sorted by end_date.
        train_ratio: Fraction for training set (default: 0.70).
        val_ratio: Fraction for validation set (default: 0.15).
        test_ratio: Fraction for test set (default: 0.15).
        purge_windows: Number of transition windows to discard at split boundaries.

    Returns:
        (train_df, val_df, test_df, purged_df)
    """
    n = len(df_group)
    if n == 0:
        empty = pd.DataFrame(columns=df_group.columns)
        return empty, empty, empty, empty

    # For very small series (< 5 windows), fall back to simple proportional cuts without purge
    if n < 5:
        n_train = max(1, int(round(n * train_ratio)))
        n_val = max(1, int(round(n * val_ratio))) if (n - n_train) > 1 else 0
        train = df_group.iloc[:n_train]
        val = df_group.iloc[n_train:n_train + n_val]
        test = df_group.iloc[n_train + n_val:]
        purged = pd.DataFrame(columns=df_group.columns)
        return train, val, test, purged

    # Standard split calculation
    train_end = int(n * train_ratio)
    val_end = int(n * (train_ratio + val_ratio))

    # Apply purge buffer at boundaries (drop boundary windows to guarantee zero overlap)
    train_cut = max(1, train_end - purge_windows)
    train_df = df_group.iloc[:train_cut]
    purge_train_val = df_group.iloc[train_cut:train_end]

    val_start = train_end
    val_cut = max(val_start + 1, val_end - purge_windows)
    val_df = df_group.iloc[val_start:val_cut]
    purge_val_test = df_group.iloc[val_cut:val_end]

    test_start = val_end
    test_df = df_group.iloc[test_start:]

    purged_df = pd.concat([purge_train_val, purge_val_test], ignore_index=True) if (len(purge_train_val) + len(purge_val_test)) > 0 else pd.DataFrame(columns=df_group.columns)

    return train_df, val_df, test_df, purged_df


def split_manifest(
    manifest_path: str,
    config_path: str = "configs/dataset_config.yaml",
    output_dir: str = "data/splits",
    group_by_asset: bool = True
) -> Dict[str, Any]:
    """Execute strict time-series split on manifest and generate JSONL files.

    Args:
        manifest_path: Path to manifest.csv generated by chart_generator.py.
        config_path: Path to dataset_config.yaml.
        output_dir: Directory where train.jsonl, val.jsonl, test.jsonl are saved.
        group_by_asset: If True, split each (asset_class, symbol, timeframe)
                        chronologically so each asset is fairly represented.

    Returns:
        Dictionary containing detailed split statistics and metadata.
    """
    manifest_file = Path(manifest_path)
    if not manifest_file.exists():
        raise FileNotFoundError(f"Manifest file not found: {manifest_path}")

    cfg = load_config(config_path)
    split_cfg = cfg.get("split_strategy", {})
    train_ratio = float(split_cfg.get("train_ratio", 0.70))
    val_ratio = float(split_cfg.get("val_ratio", 0.15))
    test_ratio = float(split_cfg.get("test_ratio", 0.15))
    purge_overlap_bars = int(split_cfg.get("purge_overlap_bars", 5))

    # In sliding window with stride=30, discarding 1 window gives a 30-bar embargo buffer (>= 5 bars)
    purge_windows = 1 if purge_overlap_bars > 0 else 0

    df = pd.read_csv(manifest_file)
    if df.empty:
        raise ValueError("Manifest file is empty.")

    # Validate required columns
    required_cols = {"image_path", "symbol", "asset_class", "timeframe", "start_date", "end_date"}
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"Manifest is missing required columns: {missing}")

    # Ensure consistent datetime sorting
    df["end_date_dt"] = pd.to_datetime(df["end_date"])
    df = df.sort_values(by=["end_date_dt", "symbol"]).reset_index(drop=True)

    train_list: List[pd.DataFrame] = []
    val_list: List[pd.DataFrame] = []
    test_list: List[pd.DataFrame] = []
    purged_list: List[pd.DataFrame] = []

    if group_by_asset:
        group_cols = ["asset_class", "symbol", "timeframe"]
        for _, group in df.groupby(group_cols, sort=False):
            group_sorted = group.sort_values(by="end_date_dt")
            tr, va, te, pu = split_series_chronological(
                group_sorted, train_ratio, val_ratio, test_ratio, purge_windows
            )
            train_list.append(tr)
            val_list.append(va)
            test_list.append(te)
            purged_list.append(pu)
    else:
        tr, va, te, pu = split_series_chronological(
            df, train_ratio, val_ratio, test_ratio, purge_windows
        )
        train_list.append(tr)
        val_list.append(va)
        test_list.append(te)
        purged_list.append(pu)

    train_df = pd.concat(train_list, ignore_index=True).sort_values(by="end_date_dt").reset_index(drop=True)
    val_df = pd.concat(val_list, ignore_index=True).sort_values(by="end_date_dt").reset_index(drop=True)
    test_df = pd.concat(test_list, ignore_index=True).sort_values(by="end_date_dt").reset_index(drop=True)
    purged_df = pd.concat(purged_list, ignore_index=True) if purged_list else pd.DataFrame()

    # Drop helper column
    for d in [train_df, val_df, test_df, purged_df]:
        if "end_date_dt" in d.columns:
            d.drop(columns=["end_date_dt"], inplace=True)

    # Export to JSONL format compatible with FinancialChartDataset
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    splits = {
        "train": train_df,
        "val": val_df,
        "test": test_df,
    }

    file_paths = {}
    for split_name, split_data in splits.items():
        jsonl_path = out_path / f"{split_name}.jsonl"
        records = []
        for idx, row in split_data.iterrows():
            rec = {
                "id": f"{split_name}_{row['symbol']}_{row['timeframe']}_{idx:04d}",
                "image_path": str(row["image_path"]),
                "symbol": str(row["symbol"]),
                "asset_class": str(row["asset_class"]),
                "timeframe": str(row["timeframe"]),
                "start_date": str(row["start_date"]),
                "end_date": str(row["end_date"]),
                "candle_count": int(row.get("candle_count", 60)),
                "detected_patterns": str(row.get("detected_patterns", "none")),
                "split": split_name,
                "instruction": DEFAULT_INSTRUCTION,
                "cot_reasoning": "",  # To be populated by CoT labeling in Step 2.4
                "action": "",         # To be populated by CoT labeling in Step 2.4
            }
            records.append(rec)

        with open(jsonl_path, "w", encoding="utf-8") as f:
            for rec in records:
                f.write(json.dumps(rec, ensure_ascii=False) + "\n")
            f.flush()
            try:
                os.fsync(f.fileno())
            except OSError:
                pass
        file_paths[split_name] = str(jsonl_path)
        logger.info(f"Saved {len(records)} records to {jsonl_path}")


    total_count = len(df)
    summary_stats = {
        "total_manifest_samples": total_count,
        "train_samples": len(train_df),
        "val_samples": len(val_df),
        "test_samples": len(test_df),
        "purged_samples": len(purged_df),
        "train_pct": round(len(train_df) / total_count * 100, 2),
        "val_pct": round(len(val_df) / total_count * 100, 2),
        "test_pct": round(len(test_df) / total_count * 100, 2),
        "purged_pct": round(len(purged_df) / total_count * 100, 2),
        "train_date_range": [train_df["start_date"].min(), train_df["end_date"].max()] if not train_df.empty else [],
        "val_date_range": [val_df["start_date"].min(), val_df["end_date"].max()] if not val_df.empty else [],
        "test_date_range": [test_df["start_date"].min(), test_df["end_date"].max()] if not test_df.empty else [],
        "asset_class_breakdown": {
            split_name: split_df["asset_class"].value_counts().to_dict()
            for split_name, split_df in splits.items()
        },
        "output_files": file_paths,
    }

    # Save summary metadata JSON for scientific logging
    summary_path = out_path / "split_summary.json"
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary_stats, f, indent=2, ensure_ascii=False)

    logger.info("Time-series split finished successfully.")
    return summary_stats
